### ISSUE TITLE
[Inquiry] How to cater for varied model deployment name in the advanced healthcheck probe

### ISSUE THREAD

**Issue by carusyte** [denlai-mshk/aoai-fwdproxy-funcapp#1]
If the deployment segment in the URL is different, how can we support that in the advanced healthcheck probe URL path config?

It seems that the probe URL setting doesn't support dynamic / parameterized path.

One way I could think of is to add one more Application Setting (environment variable) for deployment name, and rewrite the URL in handleAOAIHealthCheck.js perhaps; I could be missing better ideas though.

**Comment by denlai-mshk** [comment]
If you need multiple health checks for multiple model deployments, you can achieve this by setting up multiple backend settings in AppGW. Each backend setting should be bound to different custom health probes with unique URL paths corresponding to the model deployment names. However, keep in mind that this approach will require multiple backend pools and the replication of many function apps.

Alternatively, if you want to avoid excessive resource usage, you can consider modifying the advanced health check source code. By changing the default 'hi' message to a more challenging question, you can prompt the GPT to generate longer and more complex answers. This complicated health check can serve as a universal health check for all deployed models. This is because, when the backend infrastructure is overwhelmed, it does not distinguish between different model deployments triggered by API calls. The impact may be regional. Therefore, utilizing a single health check ensures that the backend infrastructure's response remains consistent, regardless of the specific model being accessed.

**Comment by carusyte** [comment]
Seems that, if the AOAI model deployment name varies, we would also need to rewrite the "model" parameter inside the JSON workload (message body). Otherwise "404 resource not found" if the model input parameter mismatches.

**Comment by denlai-mshk** [comment]
The API sender should indicate which AOAI model name they want to use by the API uri path. Which means, the model name is specified by the API sender, not by function app. The role of function app is just a proxy, so it should be light-weighted and without any business logic.

**Comment by denlai-mshk** [comment]
> Seems that, if the AOAI model deployment name varies, we would also need to rewrite the "model" parameter inside the JSON workload (message body). Otherwise "404 resource not found" if the model input parameter mismatches.

model name in uri path and model name in body message should be stated by the original API caller. They are business context. Forward Proxy is just a http level networking component for forwarding only.

**Comment by carusyte** [comment]
> > Seems that, if the AOAI model deployment name varies, we would also need to rewrite the "model" parameter inside the JSON workload (message body). Otherwise "404 resource not found" if the model input parameter mismatches.
> 
> model name in uri path and model name in body message should be stated by the original API caller. They are business context. Forward Proxy is just a http level networking component for forwarding only.

Totally agree on the design philosophy for the forward proxy to keep it coherent and decoupled.

The model name in request body has been figured out - there should be no further issue at this point to rely on the sender side. Typically it would just be "gpt-35-turbo" or "gpt-35-turbo-16k" regardless of the backend AOAI deployment.

On the other hand, as for the model name in the URI path, as the AOAI deployment could vary, it's infeasible for the sender side to pre-determine which AOAI deployment / backend target will be selected by AppGateway. Unless we're mandated to re-deploy the existing AOAI model using identical name to cater for the cluster setup.

**Comment by denlai-mshk** [comment]
Yes, Since AOAI RAID is shared resource, it is good to align all the deployed model name = the official model name offered like gpt-35-turbo" or "gpt-35-turbo-16k". This practice should apply to all subscriptions and all regions based.

As result, the API caller just put the targeted official model name in the API as well as the attributes inside body.
